org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true

# KMM 설정
kotlin.mpp.androidSourceSetLayoutVersion=2
kotlin.mpp.enableCInteropCommonization=true
# Windows/Linux에서 iOS Kotlin/Native 타겟 미지원 경고 억제
kotlin.native.ignoreIncorrectDependencies=true